server:
  port: 8081
  servlet:
    contextPath: /display
spring:
  application.name: display
  datasource:
    username: display
    password: display
    url: jdbc:postgresql://localhost:5432/display
  kafka:
    bootstrap-servers: "localhost:9092"
    consumer:
      group-id: "display"
