server:
  port: 8083
  servlet:
    contextPath: /recovery
spring:
  application.name: recovery
  datasource:
    username: recover
    password: recover
    url: jdbc:postgresql://localhost:5433/recover
  kafka:
    bootstrap-servers: "localhost:29092"
    consumer:
      group-id: "recovery"
management:
  endpoints:
    web:
      exposure:
        include: "*"